# Generated by Django 5.2.3 on 2026-02-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
