# Generated by Django 5.2.3 on 2025-07-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
